---
- name: Info collections
  check_mode: false
  block:
    - name: Resolve GitHub URLs
      ansible.builtin.include_tasks: resolve_github_url.yml

    - name: Get registration token (RUN ONCE)
      ansible.builtin.uri:
        url: "{{ github_full_api_url }}/registration-token"
        headers:
          Authorization: "token {{ access_token }}"
          Accept: "application/vnd.github.v3+json"
        method: POST
        status_code: 201
      register: registration
      delegate_to: localhost
      become: false
      run_once: true

    - name: "Check currently registered runners for repo {{ '(RUN ONCE)' if all_runners_in_same_repo else '' }}"
      ansible.builtin.uri:
        url: "{{ github_full_api_url }}?{{ query_params | urlencode }}"
        headers:
          Authorization: "token {{ access_token }}"
          Accept: "application/vnd.github.v3+json"
        method: GET
        status_code: 200
      vars:
        query_params:
          per_page: "{{ github_api_runners_per_page }}"
      register: registered_runners
      delegate_to: localhost
      become: false
      run_once: "{{ all_runners_in_same_repo }}"

    - name: Get Runner User IDs
      ansible.builtin.command: id -u "{{ runner_user }}"
      changed_when: false
      register: runner_user_id
      when: github_actions_system != "win"

    - name: Get Runner Group IDs
      ansible.builtin.command: id -g "{{ runner_user }}"
      changed_when: false
      register: runner_user_group_id
      when: github_actions_system != "win"

    - name: Find the latest runner version (RUN ONCE)
      ansible.builtin.uri:
        url: "https://api.github.com/repos/{{ runner_download_repository }}/releases/latest"
        headers:
          Authorization: "token {{ access_token }}"
          Content-Type: "application/json"
        method: GET
        return_content: true
        status_code: 200
        body_format: json
      check_mode: false
      register: api_response
      run_once: true
      become: false
      delegate_to: localhost
      when: runner_version == "latest"

    - name: Get systemd service facts
      ansible.builtin.service_facts:
      register: service_facts
      when: github_actions_system == "linux"
