---
- name: Set complete API url for repo runner
  ansible.builtin.set_fact:
    github_full_api_url: "{{ github_api_url }}/repos/{{ github_owner | default(github_account) }}/{{ github_repo }}/actions/runners"
  when: not runner_org and github_enterprise is not defined

- name: Set complete API url for org runner
  ansible.builtin.set_fact:
    github_full_api_url: "{{ github_api_url }}/orgs/{{ github_owner | default(github_account) }}/actions/runners"
  when: runner_org | bool and github_enterprise is not defined

- name: Set complete API url for enterprise runner
  ansible.builtin.set_fact:
    github_full_api_url: "{{ github_api_url }}/enterprises/{{ github_enterprise }}/actions/runners"
  when: github_enterprise is defined

- name: Set complete GitHub url for repo runner
  ansible.builtin.set_fact:
    github_full_url: "{{ github_url }}/{{ github_owner | default(github_account) }}/{{ github_repo }}"
  when: not runner_org and github_enterprise is not defined

- name: Set complete GitHub url for org runner
  ansible.builtin.set_fact:
    github_full_url: "{{ github_url }}/{{ github_owner | default(github_account) }}"
  when: runner_org | bool and github_enterprise is not defined

- name: Set complete GitHub url for enterprise runner
  ansible.builtin.set_fact:
    github_full_url: "{{ github_url }}/enterprises/{{ github_enterprise }}"
  when: github_enterprise is defined
